language: rust
rust:
  - nightly
cache: cargo
env:
  - CC=gcc NOLOG=1

before_cache: |
  if [[ "$TRAVIS_RUST_VERSION" == nightly ]]; then
    RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin -f
  fi

script:
- cargo clean
- cargo build
- cargo test

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == nightly ]]; then
    cargo tarpaulin --out Xml >/dev/null
    bash <(curl -s https://codecov.io/bash)
  fi