[package]
name = "haru"
version = "0.2.0"
authors = ["ffwff <mogamiriver@tuta.io>"]
documentation = "https://github.com/ffwff/hana"
homepage = "https://github.com/ffwff/hana"
repository = "https://github.com/ffwff/hana"
readme = "README.md"
license = "GPL-3.0"
edition = "2018"
build = "build.rs"

[dependencies]
decorator = { path = "./src/decorator/" }
libc = "0.2.0"
ansi_term = "0.11"
rustyline = "4.1.0"

[build-dependencies]
peg = "0.5"
cc = { version = "1.0", features = ["parallel"] }

[profile.release]
lto = true