[package]
name = "haru"
version = "0.1.0"
authors = ["ffwff <mogamiriver@tuta.io>"]
edition = "2018"
build = "build.rs"

[dependencies]
decorator = { path = "./src/decorator/" }
libc = "0.2.0"
ansi_term = "0.11"

[build-dependencies]
peg = "0.5"
cc = { version = "1.0", features = ["parallel"] }

[dev-dependencies]
rusty-fork = "0.2.1"

[profile.release]
lto = true